name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup git
        run: |-
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git config --global core.autocrlf true
          git config --global core.safecrlf false
      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Build features
        run: |
          pnpm install
          pnpm run build
      - name: Git commit
        id: commit
        run: |
          git add --all
          git commit -m "CI build"
        continue-on-error: true
      - name: Git push
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Log
        if: ${{ steps.commit.outcome != 'success' }}
        run: echo Nothing to commit.
  release:
    runs-on: ubuntu-latest
    # https://github.com/softprops/action-gh-release#permissions
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload prebuilt files to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: |
            dist/*.user.js
            README.md